# Generated by Django 2.2.3 on 2020-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewdetailsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'viewdetailsmodel',
            },
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
