# Generated by Django 2.2.3 on 2020-07-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200702_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewdetailsmodel',
            name='file',
        ),
    ]
